// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefresh = `-- name: CreateRefresh :one
INSERT INTO refresh_tokens (token, created_at, updated_at, user_id, expires_at)
VALUES (
    $1,
    NOW(),
    NOW(),
    $2,
    $3
)
RETURNING token, created_at, updated_at, user_id, expires_at, revoked_at
`

type CreateRefreshParams struct {
	Token     string
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CreateRefresh(ctx context.Context, arg CreateRefreshParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefresh, arg.Token, arg.UserID, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getRefresh = `-- name: GetRefresh :one
SELECT token, created_at, updated_at, user_id, expires_at, revoked_at
FROM refresh_tokens
WHERE token = $1
`

func (q *Queries) GetRefresh(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefresh, token)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeRefresh = `-- name: RevokeRefresh :one
UPDATE refresh_tokens
SET 
    updated_at = NOW(),
    revoked_at = NOW()
WHERE token = $1
RETURNING token
`

func (q *Queries) RevokeRefresh(ctx context.Context, token string) (string, error) {
	row := q.db.QueryRowContext(ctx, revokeRefresh, token)
	var token_2 string
	err := row.Scan(&token_2)
	return token_2, err
}
